export const GAME_BATTLESHIPS_INIT = 'GAME_BATTLESHIPS_INIT';

export const GAME_BATTLESHIPS_JOIN = 'GAME_BATTLESHIPS_JOIN';
export const GAME_BATTLESHIPS_LEAVE = 'GAME_BATTLESHIPS_LEAVE';

export const GAME_BATTLESHIPS_PLACING = 'GAME_BATTLESHIPS_PLACING';
export const GAME_BATTLESHIPS_STARTED = 'GAME_BATTLESHIPS_STARTED';
export const GAME_BATTLESHIPS_MAP_UPDATE = 'GAME_BATTLESHIPS_MAP_UPDATE';
export const GAME_BATTLESHIPS_GUESSED = 'GAME_BATTLESHIPS_GUESSED';
export const GAME_BATTLESHIPS_TURN = 'GAME_BATTLESHIPS_TURN';

export const GAME_BATTLESHIPS_PLACED_SHIPS = 'GAME_BATTLESHIPS_PLACED_SHIPS';

export const GAME_BATTLESHIPS_END = 'GAME_BATTLESHIPS_END';
// End types
export const GAME_BATTLESHIPS_RESULT_WIN = 'GAME_BATTLESHIPS_RESULT_WIN';
export const GAME_BATTLESHIPS_RESULT_LOSE = 'GAME_BATTLESHIPS_RESULT_LOSE';
export const GAME_BATTLESHIPS_RESULT_DRAW = 'GAME_BATTLESHIPS_RESULT_DRAW';
export const GAME_BATTLESHIPS_RESULT_DISCONNECTED =
  'GAME_BATTLESHIPS_RESULT_DISCONNECTED';

export const HORIZONTAL = 'HORIZONTAL';
export const VERTICAL = 'VERTICAL';

export const STATE_WAITING = 'STATE_WAITING';
export const STATE_PLACING = 'STATE_PLACING';
export const STATE_PLAY = 'STATE_PLAY';
