export const GAME_TICTACTOE_INIT = 'GAME_TICTACTOE_INIT';

export const GAME_TICTACTOE_JOIN = 'GAME_TICTACTOE_JOIN';
export const GAME_TICTACTOE_LEAVE = 'GAME_TICTACTOE_LEAVE';

export const GAME_TICTACTOE_STARTED = 'GAME_TICTACTOE_STARTED';
export const GAME_TICTACTOE_MAP_UPDATE = 'GAME_TICTACTOE_MAP_UPDATE';
export const GAME_TICTACTOE_STEPPED = 'GAME_TICTACTOE_STEPPED';
export const GAME_TICTACTOE_TURN = 'GAME_TICTACTOE_TURN';
export const GAME_TICTACTOE_END = 'GAME_TICTACTOE_END';

export const GAME_TICTACTOE_RESULT_WIN = 'GAME_TICTACTOE_RESULT_WIN';
export const GAME_TICTACTOE_RESULT_LOSE = 'GAME_TICTACTOE_RESULT_LOSE';
export const GAME_TICTACTOE_RESULT_DRAW = 'GAME_TICTACTOE_RESULT_DRAW';
export const GAME_TICTACTOE_RESULT_DISCONNECTED =
  'GAME_TICTACTOE_RESULT_DISCONNECTED';

export const GAME_TICTACTOE_O = '\u25CB';
export const GAME_TICTACTOE_X = '\u2715';
