export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_SIGNUP_ALERT_CLEAR = 'USER_SIGNUP_ALERT_CLEAR';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOGIN_ALERT_CLEAR = 'USER_LOGIN_ALERT_CLEAR';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SESSION_LOGIN_FINISHED = 'USER_SESSION_LOGIN_FINISHED';
